### ISSUE TITLE
frontend

### ISSUE THREAD

**Issue by Ulisseruiz** [asjdf/WebSerialLite#5]
Can i have a frontend folder to upgrade function?

**Comment by asjdf** [comment]
I just uploaded the original frontend page, maybe you can take a look.

**Comment by Ulisseruiz** [comment]
I need to modify html and remake c page.

**Comment by asjdf** [comment]
> I need to modify html and remake c page.


I don't quite understand

**Comment by asjdf** [comment]
Did you read the doc？

https://github.com/asjdf/WebSerialLite/tree/main/frontend#readme

**Comment by Ulisseruiz** [comment]
Ok I view now file html. In the original reposity  I can’t view this files.
