### ISSUE TITLE
Access websocket on port not equal 80

### ISSUE THREAD

**Issue by afr4283** [asjdf/WebSerialLite#6]
You might want to use
`let gateway = ``ws://${window.location.host}/webserialws``; `
instead of 
`let gateway = ``ws://${window.location.hostname + window.location.port + window.location.pathname}/webserialws``;`

That combination of hostname, port and pathname is not working at all, even on port 80, it tries to access /webserial/webserialws

**Comment by asjdf** [comment]
Thanks for the suggestion, but I don't have a test device at the moment, could you please do a PR to implement this feature?

**Comment by asjdf** [comment]
Thank you for your suggestion. This issue was solved in v2.1.0.
